version: '2'
services:
    rabbitmq:
        image: rabbitmq:management
        hostname: rabbitmq
        ports:
            - "15672:15672"
        environment:
            - RABBITMQ_ERLANG_COOKIE='mysecretpassphrase'

